#!/bin/bash
NGX_FILES=nginx-1.6.1.tar.gz
NGX_SRC=echo $NGX_FILES|sed 's/\.tar\.gz//g'
DWN_URL=http://nginx.org/download
MYSQL_FILES=mysql-5.1.17
function nginx_install()
{
    wget -c ${DWN_URL}/${NGX_FILES}
    tar zxf $NGX_FILES ; cd $NGX_SRC ;./configure;make ;make install
    if [ $? -eq 0 ];then
        echo "Success!"
    fi
}
function mysql_install()
{
    tar xzf MYSQL_FILES ; cd mysql-5.1.17;./configure --prefix=/usr/local/mysql:make ;make install
}

function php_install()
{
    if [-d /usr/local/mysql];then
 tar zxf $PHP_FILES ;cd php-5.3.3 ;./configure --prefix=/usr/localphp5 --with-mysql ; make ;make install
    else
        echo "Please pre install Mysql."
    fi
}
PS3="Please select your install Menu:"


select i in "Nginx" "Mysql" "PHP"
do
echo $i


case $1 installdo
    nginx )
    nginx_install ;;
    mysql )
    mysql_install ;;
    php )
    php_install ;;
    * )
    echo "Usage: $0 {Nginx |Mysql |PHP |Help}" ;;
esac

done
